exports.SKILLS = [
    { "name": "IT Support", "appearances": 22, "verified": true },
    { "name": "Web Development", "appearances": 22, "verified": true },
    { "name": "Graphic Design", "appearances": 22, "verified": true },
    { "name": "Video Editing", "appearances": 22, "verified": true },
    { "name": "Prompt Engineer", "appearances": 22, "verified": true },
    { "name": "Digital Marketing", "appearances": 22, "verified": true },
    { "name": "Social Media Management", "appearances": 22, "verified": true },
    { "name": "Content Management Systems (CMS)", "appearances": 22, "verified": true },
    { "name": "Database Management", "appearances": 22, "verified": true },
    { "name": "Data Analysis", "appearances": 22, "verified": true },
    { "name": "Programming", "appearances": 22, "verified": true },
    { "name": "App Development", "appearances": 22, "verified": true },
    { "name": "Cybersecurity", "appearances": 22, "verified": true },
    { "name": "Network Administration", "appearances": 22, "verified": true },
    { "name": "Audio Editing", "appearances": 22, "verified": true },
    { "name": "Animation", "appearances": 22, "verified": true },
    { "name": "Data Entry", "appearances": 22, "verified": true },
    { "name": "Office Management", "appearances": 22, "verified": true },
    { "name": "Project Management", "appearances": 22, "verified": true },
    { "name": "Scheduling", "appearances": 22, "verified": true },
    { "name": "Event Planning", "appearances": 22, "verified": true },
    { "name": "Inventory Management", "appearances": 22, "verified": true },
    { "name": "Report Writing", "appearances": 22, "verified": true },
    { "name": "Budgeting", "appearances": 22, "verified": true },
    { "name": "Record Keeping", "appearances": 22, "verified": true },
    { "name": "Compliance Management", "appearances": 22, "verified": true },
    { "name": "Public Speaking", "appearances": 22, "verified": true },
    { "name": "Writing and Editing", "appearances": 22, "verified": true },
    { "name": "Translation", "appearances": 22, "verified": true },
    { "name": "Community Outreach", "appearances": 22, "verified": true },
    { "name": "Public Relations", "appearances": 22, "verified": true },
    { "name": "Newsletter Creation", "appearances": 22, "verified": true },
    { "name": "Media Relations", "appearances": 22, "verified": true },
    { "name": "Stakeholder Engagement", "appearances": 22, "verified": true },
    { "name": "Advocacy", "appearances": 22, "verified": true },
    { "name": "Campaign Management", "appearances": 22, "verified": true },
    { "name": "Grant Writing", "appearances": 22, "verified": true },
    { "name": "Donor Relations", "appearances": 22, "verified": true },
    { "name": "Event Fundraising", "appearances": 22, "verified": true },
    { "name": "Crowdfunding", "appearances": 22, "verified": true },
    { "name": "Business Development", "appearances": 22, "verified": true },
    { "name": "Sponsorship Acquisition", "appearances": 22, "verified": true },
    { "name": "Recruitment", "appearances": 22, "verified": true },
    { "name": "Membership Programs", "appearances": 22, "verified": true },
    { "name": "Human Resources", "appearances": 22, "verified": true },
    { "name": "Finance Management", "appearances": 22, "verified": true },
    { "name": "Accounting", "appearances": 22, "verified": true },
    { "name": "Teaching", "appearances": 22, "verified": true },
    { "name": "Tutoring", "appearances": 22, "verified": true },
    { "name": "Curriculum Development", "appearances": 22, "verified": true },
    { "name": "Workshop Facilitation", "appearances": 22, "verified": true },
    { "name": "Mentoring", "appearances": 22, "verified": true },
    { "name": "Youth Development", "appearances": 22, "verified": true },
    { "name": "Career Counseling", "appearances": 22, "verified": true },
    { "name": "Educational Program Design", "appearances": 22, "verified": true },
    { "name": "Training Program Implementation", "appearances": 22, "verified": true },
    { "name": "First Aid", "appearances": 22, "verified": true },
    { "name": "Nursing", "appearances": 22, "verified": true },
    { "name": "Mental Health Counseling", "appearances": 22, "verified": true },
    { "name": "Public Health Education", "appearances": 22, "verified": true },
    { "name": "Healthcare Administration", "appearances": 22, "verified": true },
    { "name": "Emergency Response", "appearances": 22, "verified": true },
    { "name": "Nutrition Counseling", "appearances": 22, "verified": true },
    { "name": "Health Advocacy", "appearances": 22, "verified": true },
    { "name": "Sexual and Reproductive Health Education", "appearances": 22, "verified": true },
    { "name": "Painting", "appearances": 22, "verified": true },
    { "name": "Crafting", "appearances": 22, "verified": true },
    { "name": "Music Performance", "appearances": 22, "verified": true },
    { "name": "Theater Arts", "appearances": 22, "verified": true },
    { "name": "Creative Writing", "appearances": 22, "verified": true },
    { "name": "Dance Instruction", "appearances": 22, "verified": true },
    { "name": "Photography", "appearances": 22, "verified": true },
    { "name": "Graphic Design", "appearances": 22, "verified": true },
    { "name": "Illustration", "appearances": 22, "verified": true },
    { "name": "Carpentry", "appearances": 22, "verified": true },
    { "name": "Plumbing", "appearances": 22, "verified": true },
    { "name": "Electrical Work", "appearances": 22, "verified": true },
    { "name": "Gardening", "appearances": 22, "verified": true },
    { "name": "Cooking", "appearances": 22, "verified": true },
    { "name": "Driving", "appearances": 22, "verified": true },
    { "name": "Sewing", "appearances": 22, "verified": true },
    { "name": "Maintenance and Repair", "appearances": 22, "verified": true },
    { "name": "Construction", "appearances": 22, "verified": true },
    { "name": "Team Leadership", "appearances": 22, "verified": true },
    { "name": "Strategic Planning", "appearances": 22, "verified": true },
    { "name": "Risk Management", "appearances": 22, "verified": true },
    { "name": "Conflict Resolution", "appearances": 22, "verified": true },
    { "name": "Volunteer Coordination", "appearances": 22, "verified": true },
    { "name": "Organizational Development", "appearances": 22, "verified": true },
    { "name": "Board Governance", "appearances": 22, "verified": true },
    { "name": "Policy Development", "appearances": 22, "verified": true },
    { "name": "Virtual Event Planning", "appearances": 22, "verified": true },
    { "name": "Online Moderation", "appearances": 22, "verified": true },
    { "name": "Remote Team Coordination", "appearances": 22, "verified": true },
    { "name": "Digital Content Creation", "appearances": 22, "verified": true },
    { "name": "Online Teaching", "appearances": 22, "verified": true },
    { "name": "E-learning Development", "appearances": 22, "verified": true },
    { "name": "Webinar Facilitation", "appearances": 22, "verified": true },
    { "name": "Online Community Management", "appearances": 22, "verified": true },
    { "name": "Legal Research", "appearances": 22, "verified": true },
    { "name": "Paralegal Support", "appearances": 22, "verified": true },
    { "name": "Policy Analysis", "appearances": 22, "verified": true },
    { "name": "Urban Planning", "appearances": 22, "verified": true },
    { "name": "Community Development", "appearances": 22, "verified": true },
    { "name": "Social Work", "appearances": 22, "verified": true },
    { "name": "Disaster Response", "appearances": 22, "verified": true },
    { "name": "Wildlife Management", "appearances": 22, "verified": true },
    { "name": "Conservation Practices", "appearances": 22, "verified": true },
    { "name": "Habitat Restoration", "appearances": 22, "verified": true },
    { "name": "Climate Change Mitigation", "appearances": 22, "verified": true },
    { "name": "Trail Maintenance", "appearances": 22, "verified": true },
    { "name": "Fire Management", "appearances": 22, "verified": true },
    { "name": "Outdoor Safety and Survival Skills", "appearances": 22, "verified": true },
    { "name": "First Aid and CPR", "appearances": 22, "verified": true },
    { "name": "Environmental Education", "appearances": 22, "verified": true },
    { "name": "Environmental Monitoring", "appearances": 22, "verified": true },
    { "name": "Renewable Energy Systems", "appearances": 22, "verified": true },
    { "name": "Sustainable Practices Implementation", "appearances": 22, "verified": true },
    { "name": "Natural Resource Management", "appearances": 22, "verified": true },
    { "name": "Botany and Plant Identification", "appearances": 22, "verified": true },
    { "name": "Wildlife Identification and Tracking", "appearances": 22, "verified": true },
    { "name": "GIS (Geographic Information Systems)", "appearances": 22, "verified": true },
    { "name": "Community Outreach and Education", "appearances": 22, "verified": true },
    { "name": "Empathy", "appearances": 22, "verified": true },
    { "name": "Active Listening", "appearances": 22, "verified": true },
    { "name": "Adaptability", "appearances": 22, "verified": true },
    { "name": "Teamwork", "appearances": 22, "verified": true },
    { "name": "Conflict Resolution", "appearances": 22, "verified": true },
    { "name": "Negotiation", "appearances": 22, "verified": true },
    { "name": "Cultural Competency", "appearances": 22, "verified": true },
    { "name": "Motivation", "appearances": 22, "verified": true },
    { "name": "Customer Service", "appearances": 22, "verified": true },
    { "name": "Problem-Solving", "appearances": 22, "verified": true },
    { "name": "Mentorship", "appearances": 22, "verified": true },
    { "name": "Parental Support", "appearances": 22, "verified": true },
    { "name": "Elderly Care", "appearances": 22, "verified": true },
    { "name": "Animal Care", "appearances": 22, "verified": true },
    { "name": "Sports Coaching", "appearances": 22, "verified": true },
    { "name": "Fitness Training", "appearances": 22, "verified": true },
    { "name": "Yoga Instruction", "appearances": 22, "verified": true },
    { "name": "Meditation and Mindfulness", "appearances": 22, "verified": true },
    { "name": "Humanitarian Aid", "appearances": 22, "verified": true },
    { "name": "Conflict Mediation", "appearances": 22, "verified": true },
    { "name": "Crisis Intervention", "appearances": 22, "verified": true },
    { "name": "Diversity and Inclusion Training", "appearances": 22, "verified": true },
    { "name": "Ethical Hacking", "appearances": 22, "verified": true },
    { "name": "Geographic Information Systems (GIS)", "appearances": 22, "verified": true },
    { "name": "Public Transportation Advocacy", "appearances": 22, "verified": true },
    { "name": "Consumer Rights Advocacy", "appearances": 22, "verified": true },
    { "name": "Fair Trade Advocacy", "appearances": 22, "verified": true },
    { "name": "Food Security Initiatives", "appearances": 22, "verified": true },
    { "name": "Water Sanitation and Hygiene (WASH)", "appearances": 22, "verified": true },
    { "name": "Elderly Rights Advocacy", "appearances": 22, "verified": true },
    { "name": "Youth Empowerment Programs", "appearances": 22, "verified": true },
    { "name": "Disability Support Services", "appearances": 22, "verified": true },
    { "name": "Veteran Support Services", "appearances": 22, "verified": true },
    { "name": "Prison Reform Advocacy", "appearances": 22, "verified": true },
    { "name": "Immigrant and Refugee Support", "appearances": 22, "verified": true },
    { "name": "Homelessness Support", "appearances": 22, "verified": true },
    { "name": "Drug Rehabilitation Support", "appearances": 22, "verified": true },
    { "name": "LGBTQ+ Advocacy", "appearances": 22, "verified": true },
    { "name": "Women's Rights Advocacy", "appearances": 22, "verified": true },
    { "name": "Indigenous Rights Advocacy", "appearances": 22, "verified": true },
    { "name": "Rural Development", "appearances": 22, "verified": true },
    { "name": "Agricultural Development", "appearances": 22, "verified": true },
    { "name": "Fisheries Management", "appearances": 22, "verified": true },
    { "name": "Market Research", "appearances": 22, "verified": true },
    { "name": "Art Therapy", "appearances": 22, "verified": true },
    { "name": "Play Therapy", "appearances": 22, "verified": true },
    { "name": "Speech Therapy", "appearances": 22, "verified": true },
    { "name": "Occupational Therapy", "appearances": 22, "verified": true },
    { "name": "Physical Therapy", "appearances": 22, "verified": true },
    { "name": "Pet Therapy", "appearances": 22, "verified": true },
    { "name": "Community Health Work", "appearances": 22, "verified": true },
    { "name": "Urban Farming", "appearances": 22, "verified": true },
    { "name": "Waste Management", "appearances": 22, "verified": true },
    { "name": "Recycling Initiatives", "appearances": 22, "verified": true },
    { "name": "Water Conservation", "appearances": 22, "verified": true },
    { "name": "Renewable Energy Advocacy", "appearances": 22, "verified": true },
    { "name": "Sustainable Building Design", "appearances": 22, "verified": true },
    { "name": "Public Policy Advocacy", "appearances": 22, "verified": true },
    { "name": "Civic Engagement", "appearances": 22, "verified": true },
    { "name": "Human Rights Advocacy", "appearances": 22, "verified": true },
    { "name": "Legal Aid", "appearances": 22, "verified": true },
    { "name": "Peacebuilding Initiatives", "appearances": 22, "verified": true },
    { "name": "Conflict Resolution Training", "appearances": 22, "verified": true },
    { "name": "Diplomacy Skills", "appearances": 22, "verified": true },
    { "name": "Cultural Heritage Preservation", "appearances": 22, "verified": true },
    { "name": "Museum Curation", "appearances": 22, "verified": true },
    { "name": "Library Science", "appearances": 22, "verified": true },
    { "name": "Historical Research", "appearances": 22, "verified": true },
    { "name": "Genealogy Research", "appearances": 22, "verified": true },
    { "name": "Oral History Collection", "appearances": 22, "verified": true },
    { "name": "Archival Management", "appearances": 22, "verified": true },
    { "name": "Biological Research", "appearances": 22, "verified": true },
    { "name": "Chemical Research", "appearances": 22, "verified": true },
    { "name": "Physical Research", "appearances": 22, "verified": true },
    { "name": "Astronomical Research", "appearances": 22, "verified": true },
    { "name": "Environmental Research", "appearances": 22, "verified": true },
    { "name": "Social Science Research", "appearances": 22, "verified": true },
    { "name": "Economic Research", "appearances": 22, "verified": true },
    { "name": "Market Analysis", "appearances": 22, "verified": true },
    { "name": "Consumer Behavior Analysis", "appearances": 22, "verified": true },
    { "name": "Economic Development", "appearances": 22, "verified": true },
    { "name": "Financial Literacy Education", "appearances": 22, "verified": true },
    { "name": "Mandarin Chinese", "appearances": 22, "verified": true },
    { "name": "English", "appearances": 22, "verified": true },
    { "name": "Hindi", "appearances": 22, "verified": true },
    { "name": "Spanish", "appearances": 22, "verified": true },
    { "name": "French", "appearances": 22, "verified": true },
    { "name": "Arabic", "appearances": 22, "verified": true },
    { "name": "Bengali", "appearances": 22, "verified": true },
    { "name": "Russian", "appearances": 22, "verified": true },
    { "name": "Portuguese", "appearances": 22, "verified": true },
    { "name": "Urdu", "appearances": 22, "verified": true },
    { "name": "Indonesian", "appearances": 22, "verified": true },
    { "name": "German", "appearances": 22, "verified": true },
    { "name": "Japanese", "appearances": 22, "verified": true },
    { "name": "Swahili", "appearances": 22, "verified": true },
    { "name": "Marathi", "appearances": 22, "verified": true },
    { "name": "Telugu", "appearances": 22, "verified": true },
    { "name": "Turkish", "appearances": 22, "verified": true },
    { "name": "Tamil", "appearances": 22, "verified": true },
    { "name": "Vietnamese", "appearances": 22, "verified": true },
    { "name": "Korean", "appearances": 22, "verified": true },
    { "name": "Italian", "appearances": 22, "verified": true },
    { "name": "Persian (Farsi)", "appearances": 22, "verified": true },
    { "name": "Polish", "appearances": 22, "verified": true },
    { "name": "Ukrainian", "appearances": 22, "verified": true },
    { "name": "Dutch", "appearances": 22, "verified": true },
    { "name": "Thai", "appearances": 22, "verified": true },
    { "name": "Gujarati", "appearances": 22, "verified": true },
    { "name": "Kannada", "appearances": 22, "verified": true },
    { "name": "Malayalam", "appearances": 22, "verified": true },
    { "name": "Punjabi", "appearances": 22, "verified": true },
    { "name": "Greek", "appearances": 22, "verified": true },
    { "name": "Bosnian", "appearances": 22, "verified": true },
    { "name": "Croatian", "appearances": 22, "verified": true },
    { "name": "Czech", "appearances": 22, "verified": true },
    { "name": "Hungarian", "appearances": 22, "verified": true },
    { "name": "Burmese (Myanmar)", "appearances": 22, "verified": true },
    { "name": "Romanian", "appearances": 22, "verified": true },
    { "name": "Somali", "appearances": 22, "verified": true },
    { "name": "Pashto", "appearances": 22, "verified": true },
    { "name": "Filipino (Tagalog)", "appearances": 22, "verified": true },
    { "name": "Kurdish", "appearances": 22, "verified": true },
    { "name": "Bulgarian", "appearances": 22, "verified": true },
    { "name": "Slovak", "appearances": 22, "verified": true },
    { "name": "Danish", "appearances": 22, "verified": true },
    { "name": "Finnish", "appearances": 22, "verified": true },
    { "name": "Norwegian", "appearances": 22, "verified": true },
    { "name": "Croatian", "appearances": 22, "verified": true },
    { "name": "Lithuanian", "appearances": 22, "verified": true },
    { "name": "Albanian", "appearances": 22, "verified": true },
    { "name": "Georgian", "appearances": 22, "verified": true },
    { "name": "Armenian", "appearances": 22, "verified": true },
    { "name": "Mongolian", "appearances": 22, "verified": true },
    { "name": "Zulu", "appearances": 22, "verified": true },
    { "name": "Kazakh", "appearances": 22, "verified": true },
    { "name": "Tajik", "appearances": 22, "verified": true },
    { "name": "Yoruba", "appearances": 22, "verified": true },
    { "name": "Hausa", "appearances": 22, "verified": true },
    { "name": "Malagasy", "appearances": 22, "verified": true },
    { "name": "Macedonian", "appearances": 22, "verified": true }
]
