exports.SKILLS = [
    { name: "IT Support" },
    { name: "Web Development" },
    { name: "Graphic Design" },
    { name: "Video Editing" },
    { name: "Prompt Engineer" },
    { name: "Photography" },
    { name: "Digital Marketing" },
    { name: "Social Media Management" },
    { name: "Content Management Systems (CMS)" },
    { name: "Database Management" },
    { name: "Data Analysis" },
    { name: "Programming" },
    { name: "App Development" },
    { name: "Cybersecurity" },
    { name: "Network Administration" },
    { name: "Audio Editing" },
    { name: "Animation" },
    { name: "Data Entry" },
    { name: "Office Management" },
    { name: "Project Management" },
    { name: "Scheduling" },
    { name: "Event Planning" },
    { name: "Inventory Management" },
    { name: "Report Writing" },
    { name: "Budgeting" },
    { name: "Record Keeping" },
    { name: "Compliance Management" },
    { name: "Public Speaking" },
    { name: "Writing and Editing" },
    { name: "Translation" },
    { name: "Community Outreach" },
    { name: "Public Relations" },
    { name: "Newsletter Creation" },
    { name: "Media Relations" },
    { name: "Stakeholder Engagement" },
    { name: "Advocacy" },
    { name: "Campaign Management" },
    { name: "Grant Writing" },
    { name: "Donor Relations" },
    { name: "Event Fundraising" },
    { name: "Crowdfunding" },
    { name: "Business Development" },
    { name: "Sponsorship Acquisition" },
    { name: "Recruitment" },
    { name: "Membership Programs" },
    { name: "Human Resources" },
    { name: "Finance Management" },
    { name: "Accounting" },
    { name: "Teaching" },
    { name: "Tutoring" },
    { name: "Curriculum Development" },
    { name: "Workshop Facilitation" },
    { name: "Mentoring" },
    { name: "Youth Development" },
    { name: "Career Counseling" },
    { name: "Educational Program Design" },
    { name: "Training Program Implementation" },
    { name: "First Aid" },
    { name: "Nursing" },
    { name: "Mental Health Counseling" },
    { name: "Public Health Education" },
    { name: "Healthcare Administration" },
    { name: "Emergency Response" },
    { name: "Nutrition Counseling" },
    { name: "Health Advocacy" },
    { name: "Sexual and Reproductive Health Education" },
    { name: "Painting" },
    { name: "Crafting" },
    { name: "Music Performance" },
    { name: "Theater Arts" },
    { name: "Creative Writing" },
    { name: "Dance Instruction" },
    { name: "Photography" },
    { name: "Graphic Design" },
    { name: "Illustration" },
    { name: "Carpentry" },
    { name: "Plumbing" },
    { name: "Electrical Work" },
    { name: "Gardening" },
    { name: "Cooking" },
    { name: "Driving" },
    { name: "Sewing" },
    { name: "Maintenance and Repair" },
    { name: "Construction" },
    { name: "Team Leadership" },
    { name: "Strategic Planning" },
    { name: "Risk Management" },
    { name: "Conflict Resolution" },
    { name: "Volunteer Coordination" },
    { name: "Organizational Development" },
    { name: "Board Governance" },
    { name: "Policy Development" },
    { name: "Virtual Event Planning" },
    { name: "Online Moderation" },
    { name: "Remote Team Coordination" },
    { name: "Digital Content Creation" },
    { name: "Online Teaching" },
    { name: "E-learning Development" },
    { name: "Webinar Facilitation" },
    { name: "Online Community Management" },
    { name: "Legal Research" },
    { name: "Paralegal Support" },
    { name: "Policy Analysis" },
    { name: "Urban Planning" },
    { name: "Community Development" },
    { name: "Social Work" },
    { name: "Disaster Response" },
    { name: "Wildlife Management" },
    { name: "Conservation Practices" },
    { name: "Habitat Restoration" },
    { name: "Climate Change Mitigation" },
    { name: "Trail Maintenance" },
    { name: "Fire Management" },
    { name: "Outdoor Safety and Survival Skills" },
    { name: "First Aid and CPR" },
    { name: "Environmental Education" },
    { name: "Environmental Monitoring" },
    { name: "Renewable Energy Systems" },
    { name: "Sustainable Practices Implementation" },
    { name: "Natural Resource Management" },
    { name: "Botany and Plant Identification" },
    { name: "Wildlife Identification and Tracking" },
    { name: "GIS (Geographic Information Systems)" },
    { name: "Community Outreach and Education" },
    { name: "Empathy" },
    { name: "Active Listening" },
    { name: "Adaptability" },
    { name: "Teamwork" },
    { name: "Conflict Resolution" },
    { name: "Negotiation" },
    { name: "Cultural Competency" },
    { name: "Motivation" },
    { name: "Customer Service" },
    { name: "Problem-Solving" },
    { name: "Mentorship" },
    { name: "Parental Support" },
    { name: "Elderly Care" },
    { name: "Animal Care" },
    { name: "Sports Coaching" },
    { name: "Fitness Training" },
    { name: "Yoga Instruction" },
    { name: "Meditation and Mindfulness" },
    { name: "Humanitarian Aid" },
    { name: "Conflict Mediation" },
    { name: "Crisis Intervention" },
    { name: "Diversity and Inclusion Training" },
    { name: "Ethical Hacking" },
    { name: "Geographic Information Systems (GIS)" },
    { name: "Public Transportation Advocacy" },
    { name: "Consumer Rights Advocacy" },
    { name: "Fair Trade Advocacy" },
    { name: "Food Security Initiatives" },
    { name: "Water Sanitation and Hygiene (WASH)" },
    { name: "Elderly Rights Advocacy" },
    { name: "Youth Empowerment Programs" },
    { name: "Disability Support Services" },
    { name: "Veteran Support Services" },
    { name: "Prison Reform Advocacy" },
    { name: "Immigrant and Refugee Support" },
    { name: "Homelessness Support" },
    { name: "Drug Rehabilitation Support" },
    { name: "LGBTQ+ Advocacy" },
    { name: "Women's Rights Advocacy" },
    { name: "Indigenous Rights Advocacy" },
    { name: "Rural Development" },
    { name: "Agricultural Development" },
    { name: "Fisheries Management" },
    { name: "Market Research" },
    { name: "Art Therapy" },
    { name: "Play Therapy" },
    { name: "Speech Therapy" },
    { name: "Occupational Therapy" },
    { name: "Physical Therapy" },
    { name: "Pet Therapy" },
    { name: "Community Health Work" },
    { name: "Urban Farming" },
    { name: "Waste Management" },
    { name: "Recycling Initiatives" },
    { name: "Water Conservation" },
    { name: "Renewable Energy Advocacy" },
    { name: "Sustainable Building Design" },
    { name: "Public Policy Advocacy" },
    { name: "Civic Engagement" },
    { name: "Human Rights Advocacy" },
    { name: "Legal Aid" },
    { name: "Peacebuilding Initiatives" },
    { name: "Conflict Resolution Training" },
    { name: "Diplomacy Skills" },
    { name: "Cultural Heritage Preservation" },
    { name: "Museum Curation" },
    { name: "Library Science" },
    { name: "Historical Research" },
    { name: "Genealogy Research" },
    { name: "Oral History Collection" },
    { name: "Archival Management" },
    { name: "Biological Research" },
    { name: "Chemical Research" },
    { name: "Physical Research" },
    { name: "Astronomical Research" },
    { name: "Environmental Research" },
    { name: "Social Science Research" },
    { name: "Economic Research" },
    { name: "Market Analysis" },
    { name: "Consumer Behavior Analysis" },
    { name: "Economic Development" },
    { name: "Financial Literacy Education" },
    { name: "Mandarin Chinese" },
    { name: "English" },
    { name: "Hindi" },
    { name: "Spanish" },
    { name: "French" },
    { name: "Arabic" },
    { name: "Bengali" },
    { name: "Russian" },
    { name: "Portuguese" },
    { name: "Urdu" },
    { name: "Indonesian" },
    { name: "German" },
    { name: "Japanese" },
    { name: "Swahili" },
    { name: "Marathi" },
    { name: "Telugu" },
    { name: "Turkish" },
    { name: "Tamil" },
    { name: "Vietnamese" },
    { name: "Korean" },
    { name: "Italian" },
    { name: "Persian (Farsi)" },
    { name: "Polish" },
    { name: "Ukrainian" },
    { name: "Dutch" },
    { name: "Thai" },
    { name: "Gujarati" },
    { name: "Kannada" },
    { name: "Malayalam" },
    { name: "Punjabi" },
    { name: "Greek" },
    { name: "Bosnian" },
    { name: "Croatian" },
    { name: "Czech" },
    { name: "Hungarian" },
    { name: "Burmese (Myanmar)" },
    { name: "Romanian" },
    { name: "Somali" },
    { name: "Pashto" },
    { name: "Filipino (Tagalog)" },
    { name: "Kurdish" },
    { name: "Bulgarian" },
    { name: "Slovak" },
    { name: "Danish" },
    { name: "Finnish" },
    { name: "Norwegian" },
    { name: "Croatian" },
    { name: "Lithuanian" },
    { name: "Albanian" },
    { name: "Georgian" },
    { name: "Armenian" },
    { name: "Mongolian" },
    { name: "Zulu" },
    { name: "Kazakh" },
    { name: "Tajik" },
    { name: "Yoruba" },
    { name: "Hausa" },
    { name: "Malagasy" },
    { name: "Macedonian" }
]
