module.exports = {
  BookMarks: require("./bookmarks"),
  Advocate: require("./advocate"),
  SignedPetitions: require("./signedPetition"),
  Volunteers: require("./campaign/campaignVolunteers"),
  Comment: require("./comment"),  
  RepliesComment: require("./comment/reply"),
  CommentsLikes: require("./comment/likes"),
  Notification: require("./notification"),
  Replies: require("./comment/reply"),
  Message: require("./message"),
  Report: require("./report"),
  User: require("./user"),
  Issue: require("./issue/issue"),
  Impact: require("./impact/impact"),
  Campaign: require("./campaign/campaign"),
  Video: require("./video"),
  CampaignVolunteering: require("./campaign/campaignVolunteering"),
  campaignPhases: require("./campaign/campaignPhase"),
  donation: require("./campaign/campaignDonation"),
  Donated: require("./campaign/campaignDonated"),
  petitions: require("./campaign/campaignPetition"),
  Skills: require("./skills/skill"),
  College: require("./colleges"),
  SearchKeyWord: require("./search/search")
};
